### ISSUE TITLE
Upgrade to Jest 27

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack#148]
Goldstack for now uses Jest 26 but [Jest 27](https://jestjs.io/docs/getting-started) is available.

**Comment by mxro** [comment]
After upgrade, server test fails with:

```
 FAIL  src/projects.spec.ts (11.537 s)
  ● Project Endpoint › Should create, update and read project

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      19 |   });
      20 |
    > 21 |   it('Should create, update and read project', async () => {      
         |   ^
      22 |     const config: ProjectConfiguration = {
      23 |       projectName: 'project1',
      24 |       rootTemplateReference: {

      at src/projects.spec.ts:21:3
      at Object.<anonymous> (src/projects.spec.ts:10:1)
```

Could be related to https://github.com/facebook/jest/issues/11607

Solution was to ensure that `jest.setTimeout(20000);` is run before `describe(`.

**Comment by mxro** [comment]
Further errors testing esbuild build:

```
  Testing lambda build
    × Should build lambda (22 ms)
    × Should build lambda with custom esbuild config (1 ms)

  ● Testing lambda build › Should build lambda

    The service was stopped: spawn ...\esbuild-windows-64-npm-0.14.34-461e67de52-44e1b69008.zip\node_modules\esbuild-windows-64\esbuild.exe ENOENT

 ● Testing lambda build › Should build lambda with custom esbuild config    

    The service is no longer running: write EPIPE

      at ../../../../.yarn/unplugged/esbuild-npm-0.14.34-72a5e72c78/node_modules/esbuild/lib/main.js:1335:25
```

**Comment by mxro** [comment]
Raised issue related to esbuild error: https://github.com/evanw/esbuild/issues/2165 - seems to be a problem of jest/esbuild interoperability. All other tests appear to be working now.
