### ISSUE TITLE
DynamoDB Module Cannot be Loaded in Lambda `Error: Cannot find module 'testcontainers'`

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack#193]
When importing the DynamoDB module from a Lambd and running that lambda, the following error is reported:

```
2022-05-27T23:15:06.114Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'testcontainers'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'testcontainers'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by mxro** [comment]
Fixed with above PR. Will be included in next release.

**Comment by mxro** [comment]
Confirmed with [`v0.4.2`](https://github.com/goldstack/goldstack/releases/tag/v0.4.2)
