### ISSUE TITLE
Error: Cannot find module 'mock-aws-s3' when using S3 template

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack#198]
When using the s3 template in a serverless api project, the following error is shown:

```
2022-05-28T22:38:45.304Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'mock-aws-s3'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'mock-aws-s3'",
        "Require stack:",
        "- /var/task/lambda.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:726:17)",
        "    at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)",
        "    at async file:///var/runtime/index.mjs:781:15",
        "    at async file:///var/runtime/index.mjs:4:1"
    ]
}
```

This will be the same issue as https://github.com/goldstack/goldstack/issues/193

**Comment by mxro** [comment]
Confirmed fixed with [v0.4.3](https://github.com/goldstack/goldstack/releases/tag/v0.4.3).
